apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: internal-service-webhook
  name: internal-service-webhook
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: internal-service-webhook
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: internal-service-webhook
    spec:
      containers:
      - image: dougfish1/internal-service-webhook:latest
        imagePullPolicy: Always
        name: internal-service-webhook
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
