apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: internal-service-webhook
  name: internal-service-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-service-webhook
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: internal-service-webhook
    spec:
      containers:
      - image: dougfish1/internal-service-webhook:latest
        imagePullPolicy: Always
        name: internal-service-webhook
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: pbrumblay/tls-sidecar
        imagePullPolicy: Always
        name: tls-sidecar
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: secret
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token
          readOnly: true
      volumes:
      - name: secret
        secret:
          defaultMode: 420
          secretName: hook-tls
      - name: default-token
        secret:
          defaultMode: 420
          secretName: default-token-prrxg

