apiVersion: v1
kind: Service
metadata:
  name: internal-service-webhook-svc
  namespace: default
  labels:
    app: internal-service-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: internal-service-webhook
