apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: internal-service-webhook
  labels:
    app: internal-service-webhook
webhooks:
  - name: edu.mayo.dcis.internal-service-webhook
    clientConfig:
      url: https://internal-service-webhook-svc.default.svc.cluster.local/mutate
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["service"]
