apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: internal-service-webhook
  labels:
    app: internal-service-webhook
webhooks:
  - name: internal-service-webhook
    clientConfig:
      service:
        name: internal-service-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["service"]
